name: image_optimizer
description: "Optimize images by converting it to WebP and choosing the best quality/compression ratio"
publish_to: "none"
version: 1.0.3+5

environment:
  sdk: ^3.13.2

dependencies:
  code_assets: ^1.2.1
  equatable: ^2.0.7
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  hooks: ^2.2.0
  image_picker: ^1.2.1
  logging: ^1.3.0
  native_toolchain_rust: ^1.0.6
  path: ^1.9.1
  path_provider: ^2.1.6
  url_launcher: ^6.3.2

dev_dependencies:
  ffigen: ^21.0.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  msix: ^3.18.0

flutter:
  generate: true
  uses-material-design: true
  config:
    enable-swift-package-manager: true

ffigen:
  name: ImageOptimizerFFI
  description: "FFI bindings for the image_optimizer Rust library"
  output: lib/src/ffi.g.dart
  headers:
    entry-points:
      - rust/bindings.h
    include-directives:
      - "rust/bindings.h"
  functions:
    include:
      - optimize_image_ffi
  comments:
    style: any
    length: full

msix_config:
  display_name: Image Optimizer
  publisher_display_name: Pedro Mendes
  identity_name: br.eng.pedromendes.image-optimizer
  capabilities: picturesLibrary
  install_certificate: false
  languages: en-US
  publisher: "E=pedromneto97@gmail.com, CN=Pedro de Mattos Mariano Mendes Neto,
    OU=IT, O=Pedro Mendes Dev, L=Curitiba, S=Parana, C=BR"
  logo_path: logo.png
