// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Optimize an image and write it to the specified output path
///
/// # Arguments
/// * `image_path` - C string pointer to the input image file path
/// * `min_quality` - Minimum quality level (0-100)
/// * `output_path` - C string pointer to the output file path where optimized image will be written
/// * `output` - Pointer to output structure (must not be null)
///
/// # Return Value
/// Returns via the `output` parameter:
/// * `error_code = 0` on success (quality contains the selected quality level)
/// * `error_code = 1` if input file not found
/// * `error_code = 2` if failed to open input image
/// * `error_code = 3` if image type not supported
/// * `error_code = 4` if encoding failed
/// * `error_code = 5` if output file write failed
/// * `error_code = -1` if parameters are invalid (null pointers)
///
/// # Safety
/// * `image_path` must be a valid, null-terminated C string
/// * `output_path` must be a valid, null-terminated C string
/// * `output` must be a valid, non-null pointer to an OptimizeImageOutput struct
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Char>,
    ffi.Uint8,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<OptimizeImageOutput>,
  )
>()
external int optimize_image_ffi(
  ffi.Pointer<ffi.Char> image_path,
  int min_quality,
  ffi.Pointer<ffi.Char> output_path,
  ffi.Pointer<OptimizeImageOutput> output,
);

/// FFI-safe output structure
final class OptimizeImageOutput extends ffi.Struct {
  /// The quality level selected (0-100)
  @ffi.Uint8()
  external int quality;

  /// Error code: 0 = success, 1-5 = errors (see optimize_image_ffi docs)
  @ffi.Int32()
  external int error_code;
}
