// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Optimize an image and write it to the specified output path
///
/// Animated GIFs are converted to animated WebP, preserving frame delays and
/// loop count. Every other supported input produces a still WebP.
///
/// # Arguments
/// * `image_path` - C string pointer to the input image file path
/// * `min_quality` - Minimum quality level (0-100)
/// * `output_path` - C string pointer to the output file path where optimized image will be written
/// * `output` - Pointer to output structure (must not be null)
///
/// # Return Value
/// Returns via the `output` parameter:
/// * `error_code = 0` on success (quality contains the selected quality level,
/// frame_count the number of frames written)
/// * `error_code = 1` if input file not found
/// * `error_code = 2` if failed to open input image
/// * `error_code = 3` if image type not supported
/// * `error_code = 4` if encoding failed
/// * `error_code = 5` if output file write failed
/// * `error_code = 6` if the animation frames could not be decoded
/// * `error_code = 7` if animated WebP encoding failed (also reported when the
/// canvas exceeds the 16383x16383 WebP limit)
/// * `error_code = -1` if parameters are invalid (null pointers)
///
/// # Safety
/// * `image_path` must be a valid, null-terminated C string
/// * `output_path` must be a valid, null-terminated C string
/// * `output` must be a valid, non-null pointer to an OptimizeImageOutput struct
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Char>,
    ffi.Uint8,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<OptimizeImageOutput>,
  )
>()
external int optimize_image_ffi(
  ffi.Pointer<ffi.Char> image_path,
  int min_quality,
  ffi.Pointer<ffi.Char> output_path,
  ffi.Pointer<OptimizeImageOutput> output,
);

/// FFI-safe output structure
final class OptimizeImageOutput extends ffi.Struct {
  /// The quality level selected (0-100)
  @ffi.Uint8()
  external int quality;

  /// Number of frames written to the output. 1 for a still image, N for an
  /// animated WebP produced from an animated GIF.
  @ffi.Uint32()
  external int frame_count;

  /// Error code: 0 = success, 1-7 = errors (see optimize_image_ffi docs)
  @ffi.Int32()
  external int error_code;

  static ffi.Pointer<OptimizeImageOutput> $allocate(
    ffi.Allocator $allocator, {
    required int quality,
    required int frame_count,
    required int error_code,
  }) => $allocator<OptimizeImageOutput>()
    ..ref.quality = quality
    ..ref.frame_count = frame_count
    ..ref.error_code = error_code;
}
