/*
This file is automatically generated by build.rs; DO NOT MANUALLY EDIT!
This header is designed to be consumed by ffigen over on the Dart side.
*/

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * FFI-safe output structure
 */
typedef struct OptimizeImageOutput {
  /**
   * The quality level selected (0-100)
   */
  uint8_t quality;
  /**
   * Number of frames written to the output. 1 for a still image, N for an
   * animated WebP produced from an animated GIF.
   */
  uint32_t frame_count;
  /**
   * Error code: 0 = success, 1-7 = errors (see optimize_image_ffi docs)
   */
  int32_t error_code;
} OptimizeImageOutput;

/**
 * Optimize an image and write it to the specified output path
 *
 * Animated GIFs are converted to animated WebP, preserving frame delays and
 * loop count. Every other supported input produces a still WebP.
 *
 * # Arguments
 * * `image_path` - C string pointer to the input image file path
 * * `min_quality` - Minimum quality level (0-100)
 * * `output_path` - C string pointer to the output file path where optimized image will be written
 * * `output` - Pointer to output structure (must not be null)
 *
 * # Return Value
 * Returns via the `output` parameter:
 * * `error_code = 0` on success (quality contains the selected quality level,
 *   frame_count the number of frames written)
 * * `error_code = 1` if input file not found
 * * `error_code = 2` if failed to open input image
 * * `error_code = 3` if image type not supported
 * * `error_code = 4` if encoding failed
 * * `error_code = 5` if output file write failed
 * * `error_code = 6` if the animation frames could not be decoded
 * * `error_code = 7` if animated WebP encoding failed (also reported when the
 *   canvas exceeds the 16383x16383 WebP limit)
 * * `error_code = -1` if parameters are invalid (null pointers)
 *
 * # Safety
 * * `image_path` must be a valid, null-terminated C string
 * * `output_path` must be a valid, null-terminated C string
 * * `output` must be a valid, non-null pointer to an OptimizeImageOutput struct
 */
int32_t optimize_image_ffi(const char *image_path,
                           uint8_t min_quality,
                           const char *output_path,
                           struct OptimizeImageOutput *output);
